### ISSUE TITLE
MDL4.1 Exception - Call to undefined method format_topicsactivitycards::get_context()

### ISSUE THREAD

**Issue by MURBASLMS** [andrewhancox/format_topicsactivitycards#14]
line 396 of /course/format/topicsactivitycards/lib.php: Error thrown
    line 410 of /course/format/topicsactivitycards/lib.php: call to format_topicsactivitycards->get_best_editing_context()
    line 112 of /course/format/topicsactivitycards/lib.php: call to format_topicsactivitycards->texteditoroptions()
    line 1003 of /course/format/classes/base.php: call to format_topicsactivitycards->course_format_options()
    line 307 of /course/format/topics/lib.php: call to core_courseformat\base->create_edit_form_elements()
    line 281 of /course/format/topicsactivitycards/lib.php: call to format_topics->create_edit_form_elements()
    line 443 of /course/edit_form.php: call to format_topicsactivitycards->create_edit_form_elements()
    line 1024 of /lib/formslib.php: call to course_edit_form->definition_after_data()
    line 250 of /course/edit.php: call to moodleform->display()

Hi, this was working prior to updating 4.1 recently (on latest) and updating the format. Hit settings on an existing course with this format and get this error. 

Cheers

**Comment by andrewhancox** [comment]
I've just pushed a version to the plugins db and cannot reproduce this issue so am hoping it's resolved.

**Comment by MURBASLMS** [comment]
pulled again and seems to have been resolved - thanks
