### ISSUE TITLE
Empty activities's ghosts :)

### ISSUE THREAD

**Issue by Lenyman** [andrewhancox/format_topicsactivitycards#4]
Hi Andrew.
I selected this wonderful format in a course whose sections always have 4 activities inside but to my surprise some unnamed activities randomly appeared.
I investigated a bit and found that they are activities that were deleted but in the database they appear as Pending to delete (perhaps due to some error in Moodle).
In the browser's DEV Tools these phantom activities appear like this: class = "item card notavailable bg-gray020 activity type-scorm".
When I try to delete them a message says "deletion in progress" but they don't go away. Any ideas?
PS: if I change the format for any other, these activities are not taken into account (they do not appear).
Thank you!

**Comment by andrewhancox** [comment]
Is CRON definitely running correctly?

**Comment by Lenyman** [comment]
Hello. It seems definitely not: P
I removed them from the database. Cron working is something I can't fix right now.
I wonder why the other course formats don't take these errors into account ... and don't generate ghost activities.

**Comment by andrewhancox** [comment]
If cron is not running successfully every minute or so then you are going to find that a lot of aspects of your site will not be working correctly, this is an absolute requirement for Moodle not an optional additional service.

**Comment by Lenyman** [comment]
Hi Andrew. Thank you so much for your advice. I understand how important it is that Cron is working properly but I can't spend time on that for now.
Your plugin is really great, however it is the only one of the 6 installed formats that detects these strange elements. Do you have any idea about it? how to get it to ignore them? or maybe hide them and voila ?! Quick fix: =)
