### ISSUE TITLE
[3.11] editing layout broken

### ISSUE THREAD

**Issue by frumbert** [andrewhancox/format_topicsactivitycards#6]
Moving items (change order) is a mess. It looks like drag should work because of the icon next to the tile

![Screen Shot 2022-11-09 at 12 44 36 pm](https://user-images.githubusercontent.com/592257/200716291-1d460e21-39a8-48f3-92b5-1ab747413c75.png)

This icon is actually for the item to the RIGHT of it. You can't drag/change the order of the first tile in any topic because that icon is "off screen"

Clicking the move icon brings up the screen editing with tiny indicators as to where you can drag, but the tiles float over each other and its hard to figure out the screen

![Screen Shot 2022-11-09 at 12 46 21 pm](https://user-images.githubusercontent.com/592257/200716568-2aee624c-9ee9-4b53-ac36-d29094934d90.png)

The indent options (move right, move left) are still available and don't do anything.
![Screen Shot 2022-11-09 at 12 43 52 pm](https://user-images.githubusercontent.com/592257/200716145-1bcfae61-a77d-4f6c-9db7-d68b84ce0921.png)

**Comment by andrewhancox** [comment]
Should be sorted in the latest release
