### ISSUE TITLE
Errors when used in conjunction with the subcourse plugin

### ISSUE THREAD

**Issue by davefoord** [andrewhancox/format_topicsactivitycards#9]
I have a site which is using the topics activity cards format very happily, and as part of this, I use the Subcourse activity plugin (https://moodle.org/plugins/mod_subcourse) to connect courses together, including situations where where both the parent and referenced course use this format.

Last week we applied a minor security update to the Moodle, and updated a few plugins that needed updating and something that we have done has caused things to not work, in that if using the Subcourse activity - if the reference course is set to 'topics activity cards' it does take the user to the course, but immediately displays an error message and a continue button that takes them back to the parent course.

the Subcourse seems to work with all other course format combinations, hence I think the issue is for some reason sitting with this plugin.

Moodle version is [Moodle](http://moodle.org/) [4.1.6+ (Build: 20231116)](https://moodledev.io/general/releases)
Subcourse version is 2023103000
Topics Activity Cards version is 2023071102

**Comment by andrewhancox** [comment]
Can you enable the highest debugging mode and share the error message?

**Comment by davefoord** [comment]
Invalid course module ID: 5346

[More information about this error](http://docs.moodle.org/401/en/error/moodle/invalidcoursemoduleid)

Debug info:
Error code: invalidcoursemoduleid×Dismiss this notification
Stack trace:
line 242 of /lib/modinfolib.php: moodle_exception thrown
line 50 of /course/format/topicsactivitycards/format.php: call to course_modinfo->get_cm()
line 284 of /course/view.php: call to require()

**Comment by davefoord** [comment]
Thanks Andrew for responding so quickly - context of the above message, the course module id = 5346 relates to the id of the subcourse activity in the parent course - it looks like it is taking the user to the destination course, but the format is for some reason trying to display something from the course we have just come from.

**Comment by andrewhancox** [comment]
When you view the course page by following a link from viewing a course module it tries to ascertain the section so that it can pop it open if needed, I didn’t handle the scenario where you hit the course from a cm in a different course...
I’ve pushed a branch called fix_for_subcourse, let me know if that sorts it.

**Comment by davefoord** [comment]
Wow that was quick, I will get that added and let you know.

**Comment by andrewhancox** [comment]
I’m meant to be working on a legacy Mahara plugin...

**Comment by davefoord** [comment]
We have applied the fix and it works, thanks for sorting so quickly, very much appreciated.

**Comment by andrewhancox** [comment]
I’ve merged that into main_41 and it will be in the next release. Thanks for reporting the issue.
